import os

env = Environment()
env.Append(CCFLAGS = " -g -std=gnu99")

Export('env')

subobj = SConscript(['file_test/SConscript','mem_test/SConscript','mp_test/SConscript','mt_test/SConscript','signal_test/SConscript','socket_test/SConscript','sys_test/SConscript'])

obj = subobj + env.Object(Glob("*.c"))

env.Append(LINKFLAGS = '-pthread')
env.Program("rrr",list(obj))#,LIBS=['pthread'])

